module.exports = {
  USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
  USER_SIGNUP_LOADING: 'USER_SIGNUP_LOADING',
  USER_SIGNUP_ERROR: 'USER_SIGNUP_ERROR',

  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_LOADING: 'USER_LOGIN_LOADING',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',

  JSON_DATA_SAVE_SUCCESS: 'JSON_DATA_SAVE_SUCCESS',
  JSON_DATA_SAVE_ERROR: 'JSON_DATA_SAVE_ERROR',
  JSON_DATA_SAVING: 'JSON_DATA_SAVING',
};
